sudo: false

language: java

jdk:
  - openjdk7

script:
  - ./mvnw -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -B -V clean test

notifications:
  email:
    on_success: never
    on_failure: always
